// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('#main section h1').each(function(index) {
      return $(this).wrapInner('<span class="slabtext" />');
    });
    return $('.slabtext').slabText({
      viewportBreakpoint: '30em',
      headerBreakpoint: '30em'
    });
  });

}).call(this);
